---
name: Clean up old tags from ACR
trigger:
  - DTSPO-18162_cleanUpMoreACRRepos
pr: none
schedules:
  - cron: "12 5 * * Mon-Fri"
    displayName: At 05:12 on every day-of-week from Monday through Friday
    branches:
      include:
        - master
    always: "true"

parameters:
  - name: cleanup_registries
    type: object
    default:
      #hmctspublic
      #      - serviceConnection: azurerm-prod
      #        acrName: 'hmctspublic'
      #      - serviceConnection: azurerm-prod
      #        acrName: 'hmctsprivate'
      #      - serviceConnection: DTS-SHAREDSERVICES-PROD
      #        acrName: 'sdshmctspublic'
      - serviceConnection: azurerm-sandbox
        acrName: "hmctssandbox"

  - name: cleanup_patterns
    type: object
    default:
      - olderThan: "5d"
        keep: 5
        repoTagFilters: [".*:^prod.*"]
      - olderThan: "2d"
        keep: 2
        repoTagFilters: [".*:^staging-.*"]
      - olderThan: "14d"
        keep: 1
        repoTagFilters: [".*:^pr-.*"]
      - olderThan: "14d"
        keep: 1
        repoTagFilters: ["^labs/.*:.*", "^toffee.*:.*", "^plum.*:.*"]

jobs:
  - ${{ each cleanup_registry in parameters.cleanup_registries }}:
      - ${{ each cleanup_pattern in parameters.cleanup_patterns }}:
          - job:
            displayName: "${{cleanup_registry.acrName}} - ${{cleanup_pattern.tagFilter}} " # Human-readable name for the job.
            pool:
              vmImage: "ubuntu-latest"
            timeoutInMinutes: 600
            variables:
              repoTagFiltersString: ${{ join(',', cleanup_pattern.repoTagFilters) }}
            steps:
              - task: AzureCLI@1
                displayName: "Deleting ${{cleanup_pattern.tagFilter}} images from ${{cleanup_registry.acrName}} "
                inputs:
                  scriptType: bash
                  azureSubscription: ${{ cleanup_registry.serviceConnection }}
                  scriptLocation: scriptPath
                  scriptPath: scripts/cleanup-acr-old-images.sh
                  arguments: ${{cleanup_registry.acrName}} ${{cleanup_pattern.olderThan}} ${{cleanup_pattern.keep}} ${{variables.repoTagFiltersString}}
