name: ACR Cleanup (hmctssandbox)
trigger: none

pool:
  vmImage: "Ubuntu 16.04"

variables:
  serviceConnection: azurerm-sandbox
  acrName: "hmctssandbox"
  acrResourceGroup: "cnp-acr-rg"

steps:
  - template: template.yaml
    parameters:
      serviceConnection: $(serviceConnection)
      acrName: $(acrName)
      acrResourceGroup: $(acrResourceGroup)