name: ACR Cleanup (hmcts)
trigger: none

pool:
  vmImage: "Ubuntu 16.04"

variables:
  serviceConnection: azurerm-nonprod
  acrName: "hmcts"
  acrResourceGroup: "cnp-acr-rg"

steps:
  - template: template.yaml
    parameters:
      serviceConnection: $(serviceConnection)
      acrName: $(acrName)
      acrResourceGroup: $(acrResourceGroup)