---
name: Clean up old tags from ACR
trigger: none
pr: none
schedules:
  - cron: '12 5 * * Mon-Fri'
    displayName: At 05:12 on every day-of-week from Monday through Friday
    branches:
      include:
        - master
    always: 'true'


jobs:
  - template: template-image-cleanup.yaml
    parameters:
      serviceConnection: azurerm-prod
      repoRegex: '.*'
      acrName: 'hmctspublic'
      acrResourceGroup: 'rpe-acr-prod-rg'