parameters:
  serviceConnection: ''
  repoRegex: ''
  acrName: ''
  acrResourceGroup: ''

jobs:
- job:
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 600
  steps:
  - task: AzureCLI@1
    displayName: 'Delete old images'
    inputs:
      scriptType: bash
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptLocation: scriptPath
      scriptPath: scripts/cleanup-acr-old-images.sh
      arguments: ${{parameters.repoRegex}} ${{parameters.acrName}} ${{parameters.acrResourceGroup}}
