parameters:
  serviceConnection: ''
  acrName: ''
  acrResourceGroup: ''

jobs:
- job: ACR_Cleanup
  pool:
    vmImage: 'Ubuntu 16.04'
  timeoutInMinutes: 600
  steps:
  - task: AzureCLI@1
    displayName: 'Delete dangling image layers'
    inputs:
      azureSubscription:  ${{ parameters.serviceConnection }}
      scriptLocation: 'inlineScript'
      inlineScript: |
        REPOSITORIES=$(az acr repository list --name ${{ parameters.acrName }} --resource-group ${{ parameters.acrResourceGroup }} -o tsv)
        for repo in $REPOSITORIES
        do
          printf "Deleting dangling images for $repo\n"
          az acr repository show-manifests --name ${{ parameters.acrName }} --repository $repo  --query "[?!(tags[?'*'])].digest" -o tsv \
            | xargs -I% az acr repository delete --name ${{ parameters.acrName }} --image $repo@% --yes
        done