#
# Build for regenerating sealed secrets
#
name: Regenerating sealed secrets
trigger: none
pr: none
variables:
  kubernetesCluster: 'cnp-aks-sandbox-cluster'  # cnp-aks-cluster
  azureSubscription: azurerm-sandbox #azurerm-nonprod
  environment: sandbox # aat
  azureResourceGroup: cnp-aks-sandbox-rg
  keyvaultName: cftapps-sbox
- template: templates/regenerate-sealed-secrets-template.yml
