#
# Build for regenerating sealed secrets
#
name: Regenerating sealed secrets for sandbox
trigger: none
pr: none
variables:
  kubernetesCluster: 'cnp-aks-sandbox-cluster'
  azureSubscription: azurerm-sandbox
  environment: sandbox
  azureResourceGroup: cnp-aks-sandbox-rg
  keyvaultName: cftapps-sbox
  githubUserName: Flux sandbox
  githubUserEmail: flux-sandbox@hmcts.net
jobs:
- template: templates/regenerate-sealed-secrets-template.yml
