parameters:
  serviceConnection: ''
  aksResourceGroup: ''
  aksParametersFile: ''
  aksServicePrincipalId: ''
  aksServicePrincipalSecret: ''

steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'Deploy AKS Cluster'
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.aksResourceGroup }}
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'arm/templates/aks.json'
    csmParametersFile: '${{ parameters.aksParametersFile }}'
    overrideParameters: '-servicePrincipalId ${{ parameters.aksServicePrincipalId }} -servicePrincipalSecret ${{ parameters.aksServicePrincipalSecret }}'
