parameters:
  serviceConnection: ''

steps:
- task: Kubernetes@1
  displayName: 'Install or Upgrade Kured'
  enabled: true
  inputs:
    connectionType: $(kubectlConnectionType)
    azureSubscriptionEndpoint: ${{ parameters.serviceConnection }}
    azureResourceGroup: $(aksResourceGroup)
    kubernetesCluster: $(clusterName)
    command: 'apply'
    arguments: '-f manifests/kured-ds.yaml'
    outputFormat: 'name'