parameters:
  serviceConnection: ''
  aksResourceGroup: ''
  aksClusterName: ''
  
steps:
- task: Kubernetes@1
  displayName: 'Install or Upgrade Kured'
  enabled: true
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: ${{ parameters.serviceConnection }}
    azureResourceGroup: ${{ parameters.aksResourceGroup }}
    kubernetesCluster: ${{ parameters.aksClusterName }}
    command: 'apply'
    arguments: '-f manifests/kured-ds.yaml'
    outputFormat: 'name'