parameters:
  serviceConnection: ''
  aksResourceGroup: ''
  aksClusterName: ''
  environment: ''

steps:
- task: HelmDeploy@0
  displayName: 'Install or Upgrade Traefik'
  enabled: true
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: ${{ parameters.serviceConnection }}
    azureResourceGroup: ${{ parameters.aksResourceGroup }}
    kubernetesCluster: ${{ parameters.aksClusterName }}
    command: 'upgrade'
    chartType: 'Name'
    chartName: 'stable/traefik'
    namespace: 'admin'
    releaseName: 'traefik'
    valueFile: 'helm/${{ parameters.environment }}/traefik.yml'