image:
  repository: "k8s.gcr.io/etcd-amd64"
  tag: "3.3.10"
pullPolicy: "IfNotPresent"
replicas: 3
resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 1000m
    memory: 2500Mi
persistentVolume:
  enabled: true
  storage: "2Gi"
