helmOperator:
    create: true
    chartsSyncInterval: 1m
registry:
  acr:
    enabled: true
git:
  url: git@github.com:hmcts/cnp-flux-config
  path: k8s/mgmt-sandbox
  label: mgmt-sandbox
  pollInterval: 1m
additionalArgs:
- --connect=ws://fluxcloud
