imageTag: latest
loadBalancerIP: 10.99.201.97
resources:
  limits:
    cpu: 1000m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 20Mi
service:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
rbac:
  enabled: true
dashboard:
  enabled: true
  domain: sandbox-traefik.platform.hmcts.net
ssl:
  enabled: true