imageTag: 1.7.12
loadBalancerIP: 10.99.201.97
resources:
  limits:
    cpu: 1000m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 20Mi
service:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
rbac:
  enabled: true
dashboard:
  enabled: true
  domain: sandbox-traefik.platform.hmcts.net
ssl:
  enabled: true
startupArguments:
  - "--ping"
  - "--ping.entrypoint=http"
autoscaling:
  minReplicas: 2
  maxReplicas: 4
podDisruptionBudget:
  maxUnavailable: 50%