---
name: AKS Cleanup Preview
trigger: none
pr: none
variables:
  connectionType: 'Azure Resource Manager'
  containerRegistry: 'hmctspublic'  # hmctssandbox
  helmVersion: '3.2.4'
  azureSubscription: DCD-CFTAPPS-DEV  # azurerm-sandbox
  registrySubscription: azurerm-prod

resources:
  repositories:
    - repository: cnp-flux-config
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-flux-config
      endpoint: 'hmcts'
jobs:
  - job: untag_acr_image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: cnp-flux-config
    - task: Bash@3
      inputs:
        filePath: cnp-aks-pipelines/scripts/fix-image-policies.sh
        arguments: $(release_name) $(product)
