name: Preview Helm Failure Cleanup
trigger: none
pr: none
variables:
  helmVersion: 3.2.4

jobs:
  - job: DeleteFaileHelmReleases
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
    - task: HelmInstaller@1
      displayName: 'Install Helm $(helmVersion)'
      inputs:
        helmVersionToInstall: $(helmVersion)
    - task: AzureCLI@1
      displayName: 'Delete Failed Helm Releases preview 00'
      inputs:
        azureSubscription:  'DCD-CFTAPPS-DEV'
        scriptLocation: scriptPath
        scriptPath: scripts/clean-failed-release.sh
        arguments: preview-00-rg preview-00-aks
    - task: AzureCLI@1
      displayName: 'Delete Failed Helm Releases preview 01'
      inputs:
        azureSubscription:  'DCD-CFTAPPS-DEV'
        scriptLocation: scriptPath
        scriptPath: scripts/clean-failed-release.sh
        arguments: preview-01-rg preview-01-aks 