---
name: AKS Cleanup Completed Pods
trigger: none
pr: none
schedules:
  - cron: '0 * * * *'
    displayName: Clean up hour
    branches:
      include:
        - master
    always: 'true'
jobs:
  - job: DeleteCompletedPods
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
      - template: ./templates/delete-completed-pods-template.yml
        parameters:
          serviceConnection:
            - name: DCD-CFTAPPS-DEV
              clusters:
                - name: preview-00-aks
                  rg: preview-00-rg
                - name: preview-01-aks
                  rg: preview-01-rg
              namespaces:
                - rpe
            - name: DCD-CFTAPPS-STG
              clusters:
                - name: cft-aat-00-aks
                  rg: cft-aat-00-rg
                - name: cft-aat-01-aks
                  rg: cft-aat-01-rg
              namespaces:
                - rpe