---
name: AKS Cleanup Completed Pods
trigger: none
pr: none
schedules:
  - cron: '0 * * * *'
    displayName: Clean up hour
    branches:
      include:
        - master
    always: 'true'
variables:
  helmVersion: '3.2.4'
  azureSubscription: DCD-CFTAPPS-DEV

jobs:
  - job: DeleteCompletedPods
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
      - template: ./templates/delete-completed-pods-template.yml
