# see https://dev.azure.com/hmcts/Platform%20Engineering/_build?definitionId=224&_a=summary
---
name: AKS Cleanup Preview
trigger: none
pr: none
schedules:
  - cron: '0 */12 * * *'
    displayName: Clean up every 12 hours
    branches:
      include:
        - master
    always: 'true'
variables:
  helmVersion: '3.0.2'
  azureSubscription: DCD-CFTAPPS-DEV
  cutoffDays: 4

jobs:
  - job: delete_helm_release
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: sudo snap install yq
    - task: HelmInstaller@1
      displayName: 'Install Helm $(helmVersion)'
      inputs:
        helmVersionToInstall: $(helmVersion)
    - task: AzureCLI@1
      displayName: 'Delete outdated helm releases preview-00'
      inputs:
        azureSubscription:  '$(azureSubscription)'
        scriptLocation: scriptPath
        scriptPath: scripts/delete-inactive-helm-releases.sh
        arguments: preview-00-rg preview-00-aks $(cutoffDays)
    - task: AzureCLI@1
      displayName: 'Delete outdated helm releases preview-01'
      inputs:
        azureSubscription:  '$(azureSubscription)'
        scriptLocation: scriptPath
        scriptPath: scripts/delete-inactive-helm-releases.sh
        arguments: preview-01-rg preview-01-aks $(cutoffDays)
