name: Upgrade Kubernetes Service Catalog (Sandbox)
trigger: none
jobs:
- template: ../../jobs/upgrade-service-catalog.yaml
  parameters:
    serviceConnection: 'azurerm-sandbox'
    aksResourceGroup: 'cnp-aks-sandbox-rg'
    aksClusterName: 'cnp-aks-sandbox-cluster'
    helmVersion: '2.13.1'
