# https://dev.azure.com/hmcts/CNP/_build?definitionId=256&_a=summary
---
name: Monitor AKS AAT 00 Helm Releases
pr: none
schedules:
- cron: '*/2 * * * Mon-Fri'
  displayName: 'everyday'
  branches:
    include:
      - master
  always: 'true'

jobs:
  - template: template.yaml
    parameters:
      azureResourceGroup: 'aat-00-rg'
      kubernetesCluster: 'aat-00-aks'
      helmVersion: '2.16.1'
      azureSubscription: 'DCD-CFTAPPS-STG'
      vaultName: 'cftapps-stg'
      enableHelmTls: 'true'
