# see https://dev.azure.com/hmcts/CNP/_build?definitionId=257&_a=summary
---
name: Monitor AKS AAT 01 Helm Releases
trigger: none
pr: none
schedules:
  - cron: '0 8-18 * * Mon-Fri'
    displayName: Every hour Mon-Fri
    branches:
      include:
        - master
    always: 'true'

jobs:
  - template: template.yaml
    parameters:
      azureResourceGroup: 'aat-01-rg'
      kubernetesCluster: 'aat-01-aks'
      helmVersion: '2.15.2'
      azureSubscription: 'DCD-CFTAPPS-STG'
      vaultName: 'cftapps-stg'
      enableHelmTls: 'true'
