# see https://dev.azure.com/hmcts/CNP/_build?definitionId=259&_a=summary
---
name: Monitor AKS Prod 01 Helm Releases
trigger: none
pr: none
schedules:
  - cron: '0 8-18 * * Mon-Fri'
    displayName: Every hour Mon-Fri
    branches:
      include:
        - master
    always: 'true'

jobs:
  - template: template.yaml
    parameters:
      azureResourceGroup: 'prod-01-rg'
      kubernetesCluster: 'prod-01-aks'
      helmVersion: '2.16.1'
      azureSubscription: 'DCD-CFTAPPS-PROD'
      vaultName: 'cft-apps-prod'
      enableHelmTls: 'true'
