parameters:
  azureResourceGroup: ''
  kubernetesCluster: ''
  helmVersion: ''
  azureSubscription: ''
  vaultName: ''
  enableHelmTls: ''

jobs:
  - job: helm_release_status
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: AzureCLI@1
      displayName: 'Login to AKS'
      inputs:
        azureSubscription: ${{ parameters.azureSubscription }}
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group ${{parameters.azureResourceGroup}} --name ${{parameters.kubernetesCluster}}
    - task: HelmInstaller@1
      displayName: 'Install Helm ${{parameters.helmVersion}}'
      inputs:
        helmVersionToInstall: ${{parameters.helmVersion}}
    - task: AzureCLI@2
      displayName: 'Run Helm Release Status script'
      inputs:
        scriptType: bash
        azureSubscription: ${{ parameters.azureSubscription }}
        scriptLocation: scriptPath
        scriptPath: scripts/helm-release-status.sh
        arguments: ${{parameters.vaultName}} ${{parameters.enableHelmTls}} ${{parameters.kubernetesCluster}}
        failOnStandardError: true