#
# Job template for Jenkins AKS Clusters. Includes extras such as Service Catalog
#
parameters:
  serviceConnection: ''
  aksResourceGroup: ''
  aksClusterName: ''
  environment: ''
  aksParametersFile: ''

jobs:
- template: aks.yml
  parameters:
    serviceConnection: ${{ parameters.serviceConnection }}
    aksResourceGroup: ${{ parameters.aksResourceGroup }}
    aksClusterName: ${{ parameters.aksClusterName }}
    environment: ${{ parameters.environment }}
    aksParametersFile: ${{ parameters.aksParametersFile }}

- job: ServiceCatalog
  dependsOn:
  - Keyvault
  - AKS
  condition: succeeded()
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    svcatServicePrincipalSubscriptionId: $[dependencies.Keyvault.outputs['exportKeyvault.svcatServicePrincipalSubscriptionId']]
    svcatServicePrincipalId: $[dependencies.Keyvault.outputs['exportKeyvault.svcatServicePrincipalId']]
    svcatServicePrincipalSecret: $[dependencies.Keyvault.outputs['exportKeyvault.svcatServicePrincipalSecret']]
    svcatServicePrincipalTenantId: $[dependencies.Keyvault.outputs['exportKeyvault.svcatServicePrincipalTenantId']]
  steps:
  - template: ../steps/helm-init-client.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}

  - template: ../steps/service-catalog.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}
