#
# Job template for Management AKS Clusters.
#
parameters:
  serviceConnection: ''

jobs:
- template: aks.yml
  parameters:
    serviceConnection: ${{ parameters.serviceConnection }}

- job: Artifactory
  dependsOn:
  - AKS
  condition: succeeded()
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: ../steps/artifactory.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}