parameters:
  serviceConnection: ''
  aksResourceGroup: ''
  aksClusterName: ''
  aksParametersFile: ''

jobs:
- job: DeployAKS
  dependsOn: Keyvault
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    aksServicePrincipalId: $[dependencies.Keyvault.outputs['exportKeyvault.aksServicePrincipalId']]
    aksServicePrincipalSecret: $[dependencies.Keyvault.outputs['exportKeyvault.aksServicePrincipalSecret']]
  steps:
  - template: ../steps/configure-helm.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}

  - template: ../steps/deploy-aks.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}
      aksParametersFile: ${{ parameters.aksParametersFile }}