parameters:
  serviceConnection: ''
  aksResourceGroup: ''
  aksClusterName: ''
  environment: ''

jobs:
- job: InstallTraefik
  dependsOn: DeployAKS
  condition: succeeded()
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: ../steps/configure-helm.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}

  - template: $(Build.SourcesDirectory)/tasks/traefik.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}
      environment: ${{ parameters.environment }}