parameters:
  serviceConnection: ''
  aksResourceGroup: ''
  aksClusterName: ''

jobs:
- job: InstallServiceCatalog
  dependsOn:
  - Keyvault
  - DeployAKS
  condition: succeeded()
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    svcatServicePrincipalSubscriptionId: $[dependencies.Keyvault.outputs['exportKeyvault.svcatServicePrincipalSubscriptionId']]
    svcatServicePrincipalId: $[dependencies.Keyvault.outputs['exportKeyvault.svcatServicePrincipalId']]
    svcatServicePrincipalSecret: $[dependencies.Keyvault.outputs['exportKeyvault.svcatServicePrincipalSecret']]
    svcatServicePrincipalTenantId: $[dependencies.Keyvault.outputs['exportKeyvault.svcatServicePrincipalTenantId']]
  steps:
  - template: ../steps/configure-helm.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}

  - template: ../steps/service-catalog.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}