#
# Gets Keyvault secrets and maps them to variables expected by subsequent jobs
#
# For builds creating a CI (Jenkins) cluster
#
parameters:
  serviceConnection: ''

jobs:
- job: Keyvault
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: AzureKeyVault@1
    displayName: 'Get secrets from Keyvault'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      keyVaultName: $(keyvaultName)
      secretsFilter: 'aks-sp-id,aks-sp-secret,jenkins-sp-subscription-id,jenkins-sp-tenant-id,jenkins-sp-id,jenkins-sp-secret'      

  - script: |
      echo "##vso[task.setvariable variable=aksServicePrincipalId;isOutput=true]$(aks-sp-id)"
      echo "##vso[task.setvariable variable=aksServicePrincipalSecret;isOutput=true]$(aks-sp-secret)"
      echo "##vso[task.setvariable variable=svcatServicePrincipalSubscriptionId;isOutput=true]$(jenkins-sp-subscription-id)"
      echo "##vso[task.setvariable variable=svcatServicePrincipalId;isOutput=true]$(jenkins-sp-id)"
      echo "##vso[task.setvariable variable=svcatServicePrincipalSecret;isOutput=true]$(jenkins-sp-secret)"
      echo "##vso[task.setvariable variable=svcatServicePrincipalTenantId;isOutput=true]$(jenkins-sp-tenant-id)"
    displayName: 'Export Keyvault Variables'
    name: exportKeyvault