parameters:
  serviceConnection: ''
  keyvaultName: ''
  resourceGroup: ''
  postgresqlParametersFile: ''
  installPostgresql: false

jobs:
- job: Keyvault
  pool:
    vmImage: 'Ubuntu 18.04'
  steps:
  - template: ../steps/keyvault-pact.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      keyvaultName: ${{ parameters.keyvaultName }}

- job: DeployPactBroker
  dependsOn: Keyvault
  pool:
    vmImage: 'Ubuntu 18.04'
  variables:
    pactDbUser: $[dependencies.Keyvault.outputs['exportKeyvault.pactDbUser']]
    pactDbPassword: $[dependencies.Keyvault.outputs['exportKeyvault.pactDbPassword']]
  steps:
  - template: ../tasks/deploy-postgresql-arm.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      resourceGroup: ${{ parameters.resourceGroup }}
      postgresqlParametersFile: ${{ parameters.postgresqlParametersFile }}
      pactDbUser: $(pactDbUser)
      pactDbPassword: $(pactDbPassword)
      installPostgresql: ${{ parameters.installPostgresql }}
