parameters:
  serviceConnection: ''
  aksResourceGroup: ''
  aksClusterName: ''

jobs:
- job: UpgradeServiceCatalog
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: HelmInstaller@0
    inputs:
      helmVersion: "2.11.0"
      installKubectl: false
      
  - template: ../steps/helm-init-client.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}

  - template: ../tasks/helm-add-repo-svcat.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}

  - template: ../tasks/install-service-catalog.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}