jobs:
  - job: regenerate_sealed_secrets
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - task: AzureCLI@1
        displayName: 'AKS Sign in'
        inputs:
          azureSubscription: $(azureSubscription)
          scriptLocation: 'inlineScript'
          inlineScript: |
            az aks get-credentials --resource-group $(azureResourceGroup) --name $(kubernetesCluster)
      - task: AzureKeyVault@1
        displayName: 'Get git secrets from Keyvault'
        inputs:
          azureSubscription:  $(azureSubscription)
          keyVaultName:   $(keyvaultName)
          secretsFilter: 'flux-github-username,flux-github-private-key'
      - task: Bash@3
        displayName: 'Install Kubeseal'
        inputs:
          targetType: inline
          script: |
            GOOS=$(go env GOOS)
            GOARCH=$(go env GOARCH)
            wget https://github.com/bitnami/sealed-secrets/releases/download/v0.5.1/kubeseal-$GOOS-$GOARCH
            sudo install -m 755 kubeseal-$GOOS-$GOARCH /usr/local/bin/kubeseal
      - task: Bash@3
        displayName: 'Setting up Git credentials'
        env:
          GITHUB_KEY: $(flux-github-private-key)
          GITHUB_USERNAME: $(flux-github-username)
        inputs:
          targetType: filePath
          filePath: scripts/setup-github-privatekey.sh
      - task: Bash@3
        displayName: 'Refresh sealed secrets from existing'
        env:
          ENVIRONMENT: $(environment)
        inputs:
          targetType: filePath
          filePath: scripts/sealed-secrets/regenerate-sealed-secrets.sh