name: Install Pact Broker (prod)
trigger: none

variables:
  serviceConnection: azurerm-prod
  keyvaultName: "infra-vault-prod"
  resourceGroup: "pact-broker-mgmt"
  postgresqlParametersFile: 'arm/parameters/postgresql/prod.json'

jobs:
- template: ../../jobs/pact-broker.yaml
  parameters:
    serviceConnection: $(serviceConnection)
    keyvaultName: $(keyvaultName)
    resourceGroup: $(resourceGroup)
    postgresqlParametersFile: $(postgresqlParametersFile)
    installPostgresql: true
