name: Install Pact Broker (sandbox)
trigger: none

variables:
  serviceConnection: azurerm-sandbox
  keyvaultName: "infra-vault-sandbox"
  resourceGroup: "pact-broker-mgmt-sandbox"
  postgresqlParametersFile: 'arm/parameters/postgresql/sandbox.json'

jobs:
- template: ../../jobs/pact-broker.yaml
  parameters:
    serviceConnection: $(serviceConnection)
    keyvaultName: $(keyvaultName)
    resourceGroup: $(resourceGroup)
    postgresqlParametersFile: $(postgresqlParametersFile)
    installPostgresql: true