pool:
  vmImage: "Ubuntu 16.04"

variables:
  kubectlConnectionType: "Azure Resource Manager"
  aksResourceGroup: "cnp-aks-mgmt-rg"
  clusterName: "cnp-aks-mgmt-prod-cluster"
  keyvaultName: "infra-vault-prod"

steps:
  - template: template.yml
    parameters:
      serviceConnection: azurerm-prod
