#
# Job template for Management AKS Clusters.
#
parameters:
  serviceConnection: ""

jobs:
  - job: Build failure analzyer
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - template: ../../steps/build-failure-analyzer.yml.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
