---
name: AKS Cleanup Preview
trigger: none
pr: none
variables:
  connectionType: 'Azure Resource Manager'
  containerRegistry: 'hmctspublic'  # hmctssandbox
  helmVersion: '3.0.2'
  azureSubscription: DCD-CFTAPPS-DEV  # azurerm-sandbox
  registrySubscription: azurerm-prod

jobs:
  - job: untag_acr_image
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: AzureCLI@1
      displayName: 'Untag ACR image'
      enabled: true
      inputs:
        azureSubscription: $(registrySubscription)
        scriptLocation: scriptPath
        scriptPath: scripts/untag-acr-image.sh
        arguments: $(release_name) $(product) $(containerRegistry)

  - job: delete_helm_release
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: HelmInstaller@1
      displayName: 'Install Helm $(helmVersion)'
      inputs:
        helmVersionToInstall: $(helmVersion)
    - task: AzureCLI@1
      displayName: 'Helm Delete Release'
      inputs:
        azureSubscription:  '$(azureSubscription)'
        scriptLocation: scriptPath
        scriptPath: scripts/clean-pr-release.sh
        arguments: preview-00-rg preview-00-aks $(namespace) $(release_name)
    - task: AzureCLI@1
      displayName: 'Helm Delete Release'
      inputs:
        azureSubscription:  '$(azureSubscription)'
        scriptLocation: scriptPath
        scriptPath: scripts/clean-pr-release.sh
        arguments: preview-01-rg preview-01-aks $(namespace) $(release_name)
          
