---
name: AKS Cleanup Preview
trigger: none
pr: none
variables:
  connectionType: 'Azure Resource Manager'
  azureResourceGroup: 'cnp-aks-rg'  # cnp-aks-sandbox-rg
  kubernetesCluster: 'cnp-aks-cluster'  # cnp-aks-sandbox-cluster
  containerRegistry: 'hmctspublic'  # hmctssandbox
  helmVersion: '3.0.2'
  azureSubscription: azurerm-nonprod  # azurerm-sandbox
  registrySubscription: azurerm-prod

jobs:
  - job: untag_acr_image
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: AzureCLI@1
      displayName: 'Untag ACR image'
      enabled: true
      inputs:
        azureSubscription: $(registrySubscription)
        scriptLocation: 'inlineScript'
        inlineScript: |
          repository=`echo $(release_name) | sed 's/-pr-.*//' |sed '1 s/-/\//' `
          tag=`echo $(release_name) | sed "s/.*-pr-/pr-/"`
          az acr repository show-tags -n $(containerRegistry) --repository $repository --query "[?starts_with(@, '$tag')]" -o tsv \
            | xargs -I% az acr repository untag -n $(containerRegistry) --image "$repository:%"

  - job: delete_helm_release
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: HelmInstaller@1
      displayName: 'Install Helm $(helmVersion)'
      inputs:
        helmVersionToInstall: $(helmVersion)
        installKubectl: false
    - task: AzureCLI@1
      displayName: 'Helm Delete Release'
      inputs:
        azureSubscription:  '$(azureSubscription)'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group $(azureResourceGroup) --name $(kubernetesCluster)

          if [ "$(helm get values --namespace $(namespace) $(release_name) 2>/dev/null)" ]; then
            helm delete --namespace $(namespace) $(release_name)
          else
            echo "chart $(release_name) not found, doing nothing"
          fi
