name: Helm Cleanup
trigger: none
pr: none
variables:
  connectionType: 'Azure Resource Manager'
  azureResourceGroup: 'cnp-aks-rg'
  kubernetesCluster: 'cnp-aks-cluster'
  containerRegistry: 'hmcts'
  helmVersion: 2.14.0

jobs:
  - job: DeleteFaileHelmReleases
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: HelmInstaller@0
      displayName: 'Install Helm $(helmVersion)'
      inputs:
        helmVersion: $(helmVersion)
        installKubectl: false
    - task: AzureCLI@1
      displayName: 'Delete Failed Helm Releases'
      inputs:
        azureSubscription:  'azurerm-nonprod'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group $(azureResourceGroup) --name $(kubernetesCluster)
          helm init --client-only

          for release in $(helm list -q --failed); do
            helm delete --purge $release
          done