#
# Build for the Sanbox Jenkins AKS Cluster
#
variables:
  environment: 'sandbox'
  aksResourceGroup: 'cnp-aks-sandbox-rg'
  subnetResourceGroup: 'core-infra-saat'
  subnetName: 'aks-subnet'
  vnetName: 'core-infra-vnet-saat'
  location: 'uksouth'
  clusterName: 'cnp-aks-sandbox-cluster'
  nodeCount: '3'
  nodeDiskSize: '100'
  vmSize: 'Standard_D4s_v3'
  kubernetesVersion: '1.11.3'
  keyvaultName: 'infra-vault-sandbox'
  kubectlConnectionType: 'Azure Resource Manager'

jobs:
- template: ../jobs/keyvault-ci.yml
  parameters:
    serviceConnection: azurerm-sandbox
    
- template: ../jobs/aks-ci.yml
  parameters:
    serviceConnection: azurerm-sandbox