#
# Build for the Sanbox Testing AKS Cluster
#
variables:
  environment: 'test'
  aksResourceGroup: 'cnp-test-aks-rg'
  subnetResourceGroup: 'cnp-test-aks-rg'
  subnetName: 'aks-subnet'
  vnetName: 'test-vnet'
  location: 'uksouth'
  clusterName: 'cnp-test-cluster'
  nodeCount: '1'
  nodeDiskSize: '100'
  vmSize: 'Standard_D4s_v3'
  kubernetesVersion: '1.11.4'
  keyvaultName: 'infra-vault-sandbox'
  kubectlConnectionType: 'Azure Resource Manager'
  aksParametersFile: 'test.json'

jobs:
- job: Keyvault
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: ../steps/keyvault-ci.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}

- job: DeployAKS
  dependsOn: Keyvault
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    aksServicePrincipalId: $[dependencies.Keyvault.outputs['exportKeyvault.aksServicePrincipalId']]
    aksServicePrincipalSecret: $[dependencies.Keyvault.outputs['exportKeyvault.aksServicePrincipalSecret']]
  steps:
  - template: ../steps/configure-helm.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}
  - template: ../steps/deploy-aks.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}
      aksParametersFile: ${{ parameters.aksParametersFile }}

- job: InstallTraefik
  dependsOn: DeployAKS
  condition: succeeded()
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: ../steps/configure-helm.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}
  - template: ../jobs/traefik.yaml
    parameters:
      serviceConnection: azurerm-sandbox
      aksResourceGroup: $(aksResourceGroup)
      aksClusterName: $(clusterName)
      environment: $(environment)

- job: InstallKured
  dependsOn: DeployAKS
  condition: succeeded()
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: ../steps/configure-helm.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}
  - template: ../tasks/kured.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}

- job: InstallServiceCatalog
  dependsOn:
  - Keyvault
  - DeployAKS
  condition: succeeded()
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    svcatServicePrincipalSubscriptionId: $[dependencies.Keyvault.outputs['exportKeyvault.svcatServicePrincipalSubscriptionId']]
    svcatServicePrincipalId: $[dependencies.Keyvault.outputs['exportKeyvault.svcatServicePrincipalId']]
    svcatServicePrincipalSecret: $[dependencies.Keyvault.outputs['exportKeyvault.svcatServicePrincipalSecret']]
    svcatServicePrincipalTenantId: $[dependencies.Keyvault.outputs['exportKeyvault.svcatServicePrincipalTenantId']]
  steps:
  - template: ../steps/configure-helm.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}
  - template: ../steps/service-catalog.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}
  - template: ../jobs/install-kured.yaml
    parameters:
      serviceConnection: azurerm-sandbox
      aksResourceGroup: $(aksResourceGroup)
      aksClusterName: $(clusterName)