#
# Build for the Sanbox Testing AKS Cluster
#
variables:
  environment: 'test'
  aksResourceGroup: 'cnp-test-aks-rg'
  subnetResourceGroup: 'cnp-test-aks-rg'
  subnetName: 'aks-subnet'
  vnetName: 'test-vnet'
  location: 'uksouth'
  clusterName: 'cnp-test-cluster'
  nodeCount: '1'
  nodeDiskSize: '100'
  vmSize: 'Standard_D4s_v3'
  kubernetesVersion: '1.11.4'
  keyvaultName: 'infra-vault-sandbox'
  kubectlConnectionType: 'Azure Resource Manager'
  aksParametersFile: 'test.json'

jobs:
- template: ../jobs/keyvault-ci.yml
  parameters:
    serviceConnection: azurerm-sandbox

- template: ../jobs/deploy-aks.yml
  parameters:
    serviceConnection: azurerm-sandbox
    aksResourceGroup: $(aksResourceGroup)
    aksClusterName: $(clusterName)
    environment: $(environment)
    aksParametersFile: $(aksParametersFile)

- template: ../jobs/install-traefik.yaml
  parameters:
    serviceConnection: azurerm-sandbox
    aksResourceGroup: $(aksResourceGroup)
    aksClusterName: $(clusterName)
    environment: $(environment)

- template: ../jobs/install-service-catalog.yaml
  parameters:
    serviceConnection: azurerm-sandbox
    aksResourceGroup: $(aksResourceGroup)
    aksClusterName: $(clusterName)

- template: ../jobs/install-kured.yaml
  parameters:
    serviceConnection: azurerm-sandbox
    aksResourceGroup: $(aksResourceGroup)
    aksClusterName: $(clusterName)