name: Register Consul (DCD-CFTAPPS-SBOX-01)
trigger: none
pr: none

jobs:
  - template: template.yaml
    parameters:
      serviceName: $(serviceName)
      serviceAddress: 10.10.3.250
      consulAddress: 10.100.139.254
      agentPool: hmcts-agent-pool