name: Register Consul (sandbox)
trigger: none
pr: none

jobs:
  - template: template.yaml
    parameters:
      serviceName: $(serviceName)
      serviceAddress: 10.10.7.120
      consulAddress: 10.100.139.254
      agentPool: hmcts-sandbox-agent-pool