parameters:
  serviceConnection: ''
  aksResourceGroup: ''
  aksClusterName: ''
  environment: ''

steps:
- task: HelmDeploy@0
  displayName: 'Install Traefik'
  enabled: true
  inputs:
    connectionType: $(kubectlConnectionType)
    azureSubscription: ${{ parameters.serviceConnection }}
    azureResourceGroup: ${{ parameters.aksResourceGroup }}
    kubernetesCluster: ${{ parameters.aksClusterName }}
    command: 'install'
    chartType: 'Name'
    chartName: 'stable/traefik'
    namespace: 'kube-system'
    releaseName: 'traefik'
    valueFile: 'helm/${{ parameters.environment }}/traefik.yml'